# Generated by Django 6.0.6 on 2026-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
