# Generated by Django 6.0.6 on 2026-06-22 14:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hexon', '0002_vehicle_brand_vehicle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='images',
            field=wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {})}, default=''),
            preserve_default=False,
        ),
    ]
