# Generated by Django 6.0.6 on 2026-06-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexon', '0004_remove_vehicle_images_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='accessories',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
