# Generated by Django 6.0.6 on 2026-06-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexon', '0005_vehicle_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='axleconfig_svg',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
