# Generated by Django 6.0.6 on 2026-06-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexon', '0006_vehicle_axleconfig_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='axleconfig_svg',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
