# Generated by Django 6.0.6 on 2026-06-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vehicle_vehiclestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='hexon_id',
            field=models.CharField(max_length=200),
        ),
    ]
